//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmaCamTrainingTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmaCamTrainingTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] AF_import_clipper {
            get {
                object obj = ResourceManager.GetObject("AF_import_clipper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BUTTON {
            get {
                object obj = ResourceManager.GetObject("BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CLIP_CONFIGURATION {
            get {
                object obj = ResourceManager.GetObject("CLIP_CONFIGURATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CLIPPER_EXPORT_DT_DLL {
            get {
                object obj = ResourceManager.GetObject("CLIPPER_EXPORT_DT_DLL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] Clipper_Machine {
            get {
                object obj = ResourceManager.GetObject("Clipper_Machine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.Processor;
        ///using Wpm.Implement.ComponentEditor;  // ouverture de fenetres de selection almacam
        ///
        ///
        ///
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportUserCommandType : ScriptModelCustomization, IScriptMode [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Commandes_Clip {
            get {
                return ResourceManager.GetString("Commandes_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportUserEntityType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///
        ///
        ///            //preparation du dictionnaire //
        ///            // champs des [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Entities_Clip {
            get {
                return ResourceManager.GetString("Entities_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à using System;
        ///using System.IO;
        ///using System.Collections.Generic;
        ///using System.Windows.Forms;
        ///using Wpm.Schema.Kernel;
        ///using Wpm.Implement.Manager;
        ///using Wpm.Implement.ModelSetting;
        ///using Alma.BaseUI.DescriptionEditor;
        ///
        ///namespace Wpm.Implement.ModelSetting
        ///{
        ///    public partial class ImportCustomizedFormulaEventType : ScriptModelCustomization, IScriptModelCustomization
        ///    {
        ///        public override bool Execute(IContext context, IContext hostContext)
        ///        {
        ///            ITransaction transacti [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Event_Clip {
            get {
                return ResourceManager.GetString("Event_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FONDExport {
            get {
                object obj = ResourceManager.GetObject("FONDExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [SYS_USER]
        ///OleDb=Provider=PCSOFT.HFSQL;Initial Catalog=CLIPPER_ALMA;User ID=admin;Password=&quot;&quot;;Data Source=VMSR2012CLIP;
        ///DbSql=SELECT CODEEMP,PRENOMEMP,NOMEMP,ADINTERNET,TEL,DATESO DESIGN FROM EMPLOYE WHERE DATESO=&apos;&apos;
        ///EntityType=SYS_USER
        ///ImportKey=USER_NAME
        ///USER_NAME=0
        ///FIRST_NAME=1
        ///LAST_NAME=2
        ///EMAIL=3
        ///_PHONE=4
        ///
        ///[CENTRE_FRAIS]
        ///OleDb=Provider=PCSOFT.HFSQL;Initial Catalog=CLIPPER_ALMA;User ID=admin;Password=&quot;&quot;;Data Source=VMSR2012CLIP;
        ///DbSql=SELECT COFRAIS, DESIGN, DATESO FROM CFRAIS WHERE DATESO=&apos;&apos; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Import_client_1 {
            get {
                return ResourceManager.GetString("Import_client_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMPORT_CLIPPER_FOURNITURES {
            get {
                object obj = ResourceManager.GetObject("IMPORT_CLIPPER_FOURNITURES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMPORT_CLIPPER_MATERIAL {
            get {
                object obj = ResourceManager.GetObject("IMPORT_CLIPPER_MATERIAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [QUALITY]
        ///OleDb=Provider=Microsoft.Jet.OLEDB.4.0;Data Source=&quot;C:\AlmaCAM\Bin\AlmaCam_Clipper\_Clipper\Import_PrixMatieres\&quot;;Extended Properties=&quot;text;HDR=yes;FMT=Delimited&quot;
        ///DbSql=SELECT A,B,C,D,E,F/1000 FROM [Export_Nuance_Etat.csv]
        ///EntityType=_QUALITY
        ///ImportKey=_NAME
        ///_NAME=2
        ///_DENSITY=5
        ///[MATERIAL]
        ///OleDb=Provider=Microsoft.Jet.OLEDB.4.0;Data Source=&quot;C:\AlmaCAM\Bin\AlmaCam_Clipper\_Clipper\Import_PrixMatieres\&quot;;Extended Properties=&quot;text;HDR=yes;FMT=Delimited&quot;
        ///DbSql=SELECT A,B,C,D,E,F,G/1000,H FROM [E [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Import_Matiere_2 {
            get {
                return ResourceManager.GetString("Import_Matiere_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMPORT_OF {
            get {
                object obj = ResourceManager.GetObject("IMPORT_OF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IMPORT_STOCK {
            get {
                object obj = ResourceManager.GetObject("IMPORT_STOCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
